name: Android CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: macos-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.5'
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - run: flutter build ios --release --no-codesign
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          key:  /Users/runner/work/Task_Manager/Task_Manager/build/ios/iphoneos/Runner.app
      - name: Upload iOS App
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: /Users/runner/work/Task_Manager/Task_Manager/build/ios/iphoneos/Runner.app
